media:
  input: images
  output: /images

content:
  - name: pages
    label: Pages
    type: file
    path: index.html
    fields:
      - name: body
        label: Page Content
        type: code
        language: html